### ISSUE TITLE
Word Wrapping

### ISSUE THREAD

**Issue by aelleon** [SethKitchen/TheLastSliceChallenge2#1]
Hey there, I just briefly glanced over you code, but have you accounted for the case where the word wraps over the end to the beginning of the line?

ex: **roni**alskdfj**pepper**

I apologize if you have already accounted for it and I missed it. 
Good luck!

**Comment by SethKitchen** [comment]
Yes it does account for it. It will decode the line and then add it to itself. For instance line[5]+line[5] to account for wrapping. Thanks
